### ISSUE TITLE
test_trivial_g_mapping

### ISSUE THREAD

**Issue by liquidcronos** [TriPed-Robot/TriP#24]
The test test_trivial_g_mapping located in UnitTest.py fails with error:
```
ERROR: test_trivial_g_mapping (__main__.TestStates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnitTests.py", line 68, in test_trivial_g_mapping
    [{}, {'rz': radians(90)}, {'rz': radians(90)}, {}])
  File "/usr/local/lib/python3.6/dist-packages/trip_kinematics/KinematicGroup.py", line 265, in set_virtual_state
    "Error: State not set! Keys do not match! Make sure that your state includes the same keys as your intial virtual transformations.")
ValueError: Error: State not set! Keys do not match! Make sure that your state includes the same keys as your intial virtual transformations.

----------------------------------------------------------------------
```

**Comment by liquidcronos** [comment]
fixed since the test was removed
